List<String> suggestions = [
  "maharashtrian dal",
  "varan",
  "amti",
  "kalvan",
  "gujarati shaak sabzi",
  "gujarati faral, faraal",
  "maharashtrian upvas (fasting)",
  "dinner",
  "sabzis with gravies",
  "sankashti chaturthi",
  "faraal",
  "gujarati faral",
  "kadhi recipes from all across india",
  "ekadasi",
  "ekadashi recipes",
  "ekadasi",
  "quick kadhis",
  "gujarati khichdi",
  "traditional indian rice recipes",
  "maharashtrian bhaat (rice)",
  "maharashtrian sweet dishes",
  "dry fruit flavours",
  "traditional indian mithai",
  "diwali sweets mithai",
  "ganesh chaturthi",
  "maharashtrian bhaji",
  "one meal dinner",
  "saute",
  "pan",
  "indian tawa",
  "gujarati khichdi",
  "maharashtrian dal, varan / amti / kalvan",
  "evening tea snacks",
  "maharashtrian breakfast",
  "baked snacks",
  "maharashtrian snacks nashta",
  "healthy indian jar snacks",
  "rotis",
  "polis",
  "mahashivaratri",
  "janmashtami",
  "navratri vrat",
  "frozen foods indian gravies",
  "gujarati sweet mithai",
  "gudi padwa",
  "vegan indian curries",
  "gujarati faral, faraal",
  "sukhi sabzis",
  "breakfast",
  "mumbai street food",
  "easy, simple indian snack",
  "fast",
  "street food",
  "cheese sandwich",
  "south indian chutney",
  "pickles",
  "maharashtrian pickles",
  "chutney",
  "coffee",
  "high tea party",
  "tea",
  "evening tea snacks",
  "snacks",
  "ice creams",
  "one meal dinner",
  "dosa",
  "idlis",
  "uttapam",
  "barfi recipes",
  "indian mocktails",
  "holi",
  "toast sandwich",
  "leafy vegetable sabzis",
  "punjabi rotis",
  "parathas",
  "janmashtami",
  "achar",
  "raitas",
  "easy vegetarian curry",
];
